# Site Specific Configuration
name: Awesome Rovers
description: Discover a world of rovers from NASA, student projects, DIY builds, and educational creations! Dive into fascinating stories, innovations, and unique features of each rover exploring our planet and beyond.
url: https://dsonyy.github.io/awesome-rovers
author: dsonyy

# Post summary
excerpt_separator: <!--more-->

# Keywords
keywords: ["seo", "key", "words"]

# Collections
collections:
  rovers:
    output: true
    permalink: /rovers/:path/
    layout: "post"
    order: "asc"
    sort_by: "title"

# Defaults
defaults:
  - scope:
      path: "_rovers/"
    values:
      title: Untitled
      categories:
      layout: post
      read_more: false
      rover:
        designer:
          text: N/D
        launch:
          text: N/D
        mission:
          text: N/D
        destination:
          text: N/D
        status:
          text: N/D
        weight:
          text: N/D
        dimensions:
          text: N/D

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Exclusions
exclude: ["README.md", "LICENSE", "_rovers/_template.md"]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
