# Site Specific Configuration
name: Awesome Rovers
description: Discover a world of rovers from NASA, student projects, DIY builds, and educational creations! Dive into fascinating stories, innovations, and unique features of each rover exploring our planet and beyond.
url: https://dsonyy.github.io/awesomerovers
author: dsonyy

# Post summary
excerpt_separator: <!--more-->

# Keywords
keywords: ["seo", "key", "words"]

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: "your.site.fqdn"
    script_source: "https://plausible.io/js/script.js"

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Category Paginating
autopages:
  enabled: true
  categories:
    title: "Posts in category :cat"
    permalink: "/category/:cat"
    silent: false

# Exclusions
exclude: ["README.md", "LICENSE"]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
