# Site Specific Configuration
name: Awesome Rovers
description: Discover a world of rovers from NASA, student projects, DIY builds, and educational creations! Dive into fascinating stories, innovations, and unique features of each rover exploring our planet and beyond.
url: https://dsonyy.github.io/awesome-rovers
author: dsonyy

# Post summary
excerpt_separator: <!--more-->

# Keywords
keywords: ["seo", "key", "words"]

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Exclusions
exclude: ["README.md", "LICENSE"]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
